//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BugTrackerEntityModels", "FK_tbl_Users_tbl_UserProfile", "tbl_UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BugTracker.Data.tbl_UserProfile), "tbl_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BugTracker.Data.tbl_Users), true)]
[assembly: EdmRelationshipAttribute("BugTrackerEntityModels", "FK_tbl_ProjectBugsMapping_tbl_Bugs", "tbl_Bugs", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BugTracker.Data.tbl_Bugs), "tbl_ProjectBugsMapping", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BugTracker.Data.tbl_ProjectBugsMapping), true)]
[assembly: EdmRelationshipAttribute("BugTrackerEntityModels", "FK_tbl_ProjectBugsMapping_tbl_Projects", "tbl_Projects", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BugTracker.Data.tbl_Projects), "tbl_ProjectBugsMapping", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BugTracker.Data.tbl_ProjectBugsMapping), true)]
[assembly: EdmRelationshipAttribute("BugTrackerEntityModels", "FK_tbl_UserProjectsMapping_tbl_Projects", "tbl_Projects", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BugTracker.Data.tbl_Projects), "tbl_UserProjectsMapping", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BugTracker.Data.tbl_UserProjectsMapping), true)]
[assembly: EdmRelationshipAttribute("BugTrackerEntityModels", "FK_tbl_UserProjectsMapping_tbl_Users", "tbl_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BugTracker.Data.tbl_Users), "tbl_UserProjectsMapping", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BugTracker.Data.tbl_UserProjectsMapping), true)]
[assembly: EdmRelationshipAttribute("BugTrackerEntityModels", "FK_tbl_BugCommentsMapping_tbl_Bugs", "tbl_Bugs", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BugTracker.Data.tbl_Bugs), "tbl_BugCommentsMapping", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BugTracker.Data.tbl_BugCommentsMapping), true)]
[assembly: EdmRelationshipAttribute("BugTrackerEntityModels", "FK_tbl_BugCommentsMapping_tbl_Comments", "tbl_Comments", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BugTracker.Data.tbl_Comments), "tbl_BugCommentsMapping", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BugTracker.Data.tbl_BugCommentsMapping), true)]
[assembly: EdmRelationshipAttribute("BugTrackerEntityModels", "FK_tbl_Users_tbl_UserType", "tbl_UserType", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(BugTracker.Data.tbl_UserType), "tbl_Users", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BugTracker.Data.tbl_Users), true)]

#endregion

namespace BugTracker.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BugTrackerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BugTrackerEntities object using the connection string found in the 'BugTrackerEntities' section of the application configuration file.
        /// </summary>
        public BugTrackerEntities() : base("name=BugTrackerEntities", "BugTrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BugTrackerEntities object.
        /// </summary>
        public BugTrackerEntities(string connectionString) : base(connectionString, "BugTrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BugTrackerEntities object.
        /// </summary>
        public BugTrackerEntities(EntityConnection connection) : base(connection, "BugTrackerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Users> tbl_Users
        {
            get
            {
                if ((_tbl_Users == null))
                {
                    _tbl_Users = base.CreateObjectSet<tbl_Users>("tbl_Users");
                }
                return _tbl_Users;
            }
        }
        private ObjectSet<tbl_Users> _tbl_Users;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Bugs> tbl_Bugs
        {
            get
            {
                if ((_tbl_Bugs == null))
                {
                    _tbl_Bugs = base.CreateObjectSet<tbl_Bugs>("tbl_Bugs");
                }
                return _tbl_Bugs;
            }
        }
        private ObjectSet<tbl_Bugs> _tbl_Bugs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Comments> tbl_Comments
        {
            get
            {
                if ((_tbl_Comments == null))
                {
                    _tbl_Comments = base.CreateObjectSet<tbl_Comments>("tbl_Comments");
                }
                return _tbl_Comments;
            }
        }
        private ObjectSet<tbl_Comments> _tbl_Comments;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Projects> tbl_Projects
        {
            get
            {
                if ((_tbl_Projects == null))
                {
                    _tbl_Projects = base.CreateObjectSet<tbl_Projects>("tbl_Projects");
                }
                return _tbl_Projects;
            }
        }
        private ObjectSet<tbl_Projects> _tbl_Projects;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_UserProfile> tbl_UserProfile
        {
            get
            {
                if ((_tbl_UserProfile == null))
                {
                    _tbl_UserProfile = base.CreateObjectSet<tbl_UserProfile>("tbl_UserProfile");
                }
                return _tbl_UserProfile;
            }
        }
        private ObjectSet<tbl_UserProfile> _tbl_UserProfile;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_ProjectBugsMapping> tbl_ProjectBugsMapping
        {
            get
            {
                if ((_tbl_ProjectBugsMapping == null))
                {
                    _tbl_ProjectBugsMapping = base.CreateObjectSet<tbl_ProjectBugsMapping>("tbl_ProjectBugsMapping");
                }
                return _tbl_ProjectBugsMapping;
            }
        }
        private ObjectSet<tbl_ProjectBugsMapping> _tbl_ProjectBugsMapping;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_UserProjectsMapping> tbl_UserProjectsMapping
        {
            get
            {
                if ((_tbl_UserProjectsMapping == null))
                {
                    _tbl_UserProjectsMapping = base.CreateObjectSet<tbl_UserProjectsMapping>("tbl_UserProjectsMapping");
                }
                return _tbl_UserProjectsMapping;
            }
        }
        private ObjectSet<tbl_UserProjectsMapping> _tbl_UserProjectsMapping;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_BugCommentsMapping> tbl_BugCommentsMapping
        {
            get
            {
                if ((_tbl_BugCommentsMapping == null))
                {
                    _tbl_BugCommentsMapping = base.CreateObjectSet<tbl_BugCommentsMapping>("tbl_BugCommentsMapping");
                }
                return _tbl_BugCommentsMapping;
            }
        }
        private ObjectSet<tbl_BugCommentsMapping> _tbl_BugCommentsMapping;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_UserType> tbl_UserType
        {
            get
            {
                if ((_tbl_UserType == null))
                {
                    _tbl_UserType = base.CreateObjectSet<tbl_UserType>("tbl_UserType");
                }
                return _tbl_UserType;
            }
        }
        private ObjectSet<tbl_UserType> _tbl_UserType;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Users(tbl_Users tbl_Users)
        {
            base.AddObject("tbl_Users", tbl_Users);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Bugs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Bugs(tbl_Bugs tbl_Bugs)
        {
            base.AddObject("tbl_Bugs", tbl_Bugs);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Comments EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Comments(tbl_Comments tbl_Comments)
        {
            base.AddObject("tbl_Comments", tbl_Comments);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Projects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Projects(tbl_Projects tbl_Projects)
        {
            base.AddObject("tbl_Projects", tbl_Projects);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_UserProfile EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_UserProfile(tbl_UserProfile tbl_UserProfile)
        {
            base.AddObject("tbl_UserProfile", tbl_UserProfile);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_ProjectBugsMapping EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_ProjectBugsMapping(tbl_ProjectBugsMapping tbl_ProjectBugsMapping)
        {
            base.AddObject("tbl_ProjectBugsMapping", tbl_ProjectBugsMapping);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_UserProjectsMapping EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_UserProjectsMapping(tbl_UserProjectsMapping tbl_UserProjectsMapping)
        {
            base.AddObject("tbl_UserProjectsMapping", tbl_UserProjectsMapping);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_BugCommentsMapping EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_BugCommentsMapping(tbl_BugCommentsMapping tbl_BugCommentsMapping)
        {
            base.AddObject("tbl_BugCommentsMapping", tbl_BugCommentsMapping);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_UserType EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_UserType(tbl_UserType tbl_UserType)
        {
            base.AddObject("tbl_UserType", tbl_UserType);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackerEntityModels", Name="tbl_BugCommentsMapping")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_BugCommentsMapping : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_BugCommentsMapping object.
        /// </summary>
        /// <param name="mappingID">Initial value of the MappingID property.</param>
        public static tbl_BugCommentsMapping Createtbl_BugCommentsMapping(global::System.Guid mappingID)
        {
            tbl_BugCommentsMapping tbl_BugCommentsMapping = new tbl_BugCommentsMapping();
            tbl_BugCommentsMapping.MappingID = mappingID;
            return tbl_BugCommentsMapping;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid MappingID
        {
            get
            {
                return _MappingID;
            }
            set
            {
                if (_MappingID != value)
                {
                    OnMappingIDChanging(value);
                    ReportPropertyChanging("MappingID");
                    _MappingID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MappingID");
                    OnMappingIDChanged();
                }
            }
        }
        private global::System.Guid _MappingID;
        partial void OnMappingIDChanging(global::System.Guid value);
        partial void OnMappingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> BugID
        {
            get
            {
                return _BugID;
            }
            set
            {
                OnBugIDChanging(value);
                ReportPropertyChanging("BugID");
                _BugID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BugID");
                OnBugIDChanged();
            }
        }
        private Nullable<global::System.Guid> _BugID;
        partial void OnBugIDChanging(Nullable<global::System.Guid> value);
        partial void OnBugIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CommentID
        {
            get
            {
                return _CommentID;
            }
            set
            {
                OnCommentIDChanging(value);
                ReportPropertyChanging("CommentID");
                _CommentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommentID");
                OnCommentIDChanged();
            }
        }
        private Nullable<global::System.Guid> _CommentID;
        partial void OnCommentIDChanging(Nullable<global::System.Guid> value);
        partial void OnCommentIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_BugCommentsMapping_tbl_Bugs", "tbl_Bugs")]
        public tbl_Bugs tbl_Bugs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Bugs>("BugTrackerEntityModels.FK_tbl_BugCommentsMapping_tbl_Bugs", "tbl_Bugs").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Bugs>("BugTrackerEntityModels.FK_tbl_BugCommentsMapping_tbl_Bugs", "tbl_Bugs").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Bugs> tbl_BugsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Bugs>("BugTrackerEntityModels.FK_tbl_BugCommentsMapping_tbl_Bugs", "tbl_Bugs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Bugs>("BugTrackerEntityModels.FK_tbl_BugCommentsMapping_tbl_Bugs", "tbl_Bugs", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_BugCommentsMapping_tbl_Comments", "tbl_Comments")]
        public tbl_Comments tbl_Comments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Comments>("BugTrackerEntityModels.FK_tbl_BugCommentsMapping_tbl_Comments", "tbl_Comments").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Comments>("BugTrackerEntityModels.FK_tbl_BugCommentsMapping_tbl_Comments", "tbl_Comments").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Comments> tbl_CommentsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Comments>("BugTrackerEntityModels.FK_tbl_BugCommentsMapping_tbl_Comments", "tbl_Comments");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Comments>("BugTrackerEntityModels.FK_tbl_BugCommentsMapping_tbl_Comments", "tbl_Comments", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackerEntityModels", Name="tbl_Bugs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Bugs : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Bugs object.
        /// </summary>
        /// <param name="bugID">Initial value of the BugID property.</param>
        public static tbl_Bugs Createtbl_Bugs(global::System.Guid bugID)
        {
            tbl_Bugs tbl_Bugs = new tbl_Bugs();
            tbl_Bugs.BugID = bugID;
            return tbl_Bugs;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid BugID
        {
            get
            {
                return _BugID;
            }
            set
            {
                if (_BugID != value)
                {
                    OnBugIDChanging(value);
                    ReportPropertyChanging("BugID");
                    _BugID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("BugID");
                    OnBugIDChanged();
                }
            }
        }
        private global::System.Guid _BugID;
        partial void OnBugIDChanging(global::System.Guid value);
        partial void OnBugIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Screenshots
        {
            get
            {
                return StructuralObject.GetValidValue(_Screenshots);
            }
            set
            {
                OnScreenshotsChanging(value);
                ReportPropertyChanging("Screenshots");
                _Screenshots = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Screenshots");
                OnScreenshotsChanged();
            }
        }
        private global::System.Byte[] _Screenshots;
        partial void OnScreenshotsChanging(global::System.Byte[] value);
        partial void OnScreenshotsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> OpenDate
        {
            get
            {
                return _OpenDate;
            }
            set
            {
                OnOpenDateChanging(value);
                ReportPropertyChanging("OpenDate");
                _OpenDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OpenDate");
                OnOpenDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _OpenDate;
        partial void OnOpenDateChanging(Nullable<global::System.DateTime> value);
        partial void OnOpenDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ClosedDate
        {
            get
            {
                return _ClosedDate;
            }
            set
            {
                OnClosedDateChanging(value);
                ReportPropertyChanging("ClosedDate");
                _ClosedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClosedDate");
                OnClosedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ClosedDate;
        partial void OnClosedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnClosedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private Nullable<global::System.Int16> _Status;
        partial void OnStatusChanging(Nullable<global::System.Int16> value);
        partial void OnStatusChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_ProjectBugsMapping_tbl_Bugs", "tbl_ProjectBugsMapping")]
        public EntityCollection<tbl_ProjectBugsMapping> tbl_ProjectBugsMapping
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_ProjectBugsMapping>("BugTrackerEntityModels.FK_tbl_ProjectBugsMapping_tbl_Bugs", "tbl_ProjectBugsMapping");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_ProjectBugsMapping>("BugTrackerEntityModels.FK_tbl_ProjectBugsMapping_tbl_Bugs", "tbl_ProjectBugsMapping", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_BugCommentsMapping_tbl_Bugs", "tbl_BugCommentsMapping")]
        public EntityCollection<tbl_BugCommentsMapping> tbl_BugCommentsMapping
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_BugCommentsMapping>("BugTrackerEntityModels.FK_tbl_BugCommentsMapping_tbl_Bugs", "tbl_BugCommentsMapping");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_BugCommentsMapping>("BugTrackerEntityModels.FK_tbl_BugCommentsMapping_tbl_Bugs", "tbl_BugCommentsMapping", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackerEntityModels", Name="tbl_Comments")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Comments : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Comments object.
        /// </summary>
        /// <param name="commentID">Initial value of the CommentID property.</param>
        public static tbl_Comments Createtbl_Comments(global::System.Guid commentID)
        {
            tbl_Comments tbl_Comments = new tbl_Comments();
            tbl_Comments.CommentID = commentID;
            return tbl_Comments;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid CommentID
        {
            get
            {
                return _CommentID;
            }
            set
            {
                if (_CommentID != value)
                {
                    OnCommentIDChanging(value);
                    ReportPropertyChanging("CommentID");
                    _CommentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CommentID");
                    OnCommentIDChanged();
                }
            }
        }
        private global::System.Guid _CommentID;
        partial void OnCommentIDChanging(global::System.Guid value);
        partial void OnCommentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comment
        {
            get
            {
                return _Comment;
            }
            set
            {
                OnCommentChanging(value);
                ReportPropertyChanging("Comment");
                _Comment = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comment");
                OnCommentChanged();
            }
        }
        private global::System.String _Comment;
        partial void OnCommentChanging(global::System.String value);
        partial void OnCommentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CommentDate
        {
            get
            {
                return _CommentDate;
            }
            set
            {
                OnCommentDateChanging(value);
                ReportPropertyChanging("CommentDate");
                _CommentDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CommentDate");
                OnCommentDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CommentDate;
        partial void OnCommentDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCommentDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_BugCommentsMapping_tbl_Comments", "tbl_BugCommentsMapping")]
        public EntityCollection<tbl_BugCommentsMapping> tbl_BugCommentsMapping
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_BugCommentsMapping>("BugTrackerEntityModels.FK_tbl_BugCommentsMapping_tbl_Comments", "tbl_BugCommentsMapping");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_BugCommentsMapping>("BugTrackerEntityModels.FK_tbl_BugCommentsMapping_tbl_Comments", "tbl_BugCommentsMapping", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackerEntityModels", Name="tbl_ProjectBugsMapping")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_ProjectBugsMapping : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_ProjectBugsMapping object.
        /// </summary>
        /// <param name="mappingID">Initial value of the MappingID property.</param>
        public static tbl_ProjectBugsMapping Createtbl_ProjectBugsMapping(global::System.Guid mappingID)
        {
            tbl_ProjectBugsMapping tbl_ProjectBugsMapping = new tbl_ProjectBugsMapping();
            tbl_ProjectBugsMapping.MappingID = mappingID;
            return tbl_ProjectBugsMapping;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid MappingID
        {
            get
            {
                return _MappingID;
            }
            set
            {
                if (_MappingID != value)
                {
                    OnMappingIDChanging(value);
                    ReportPropertyChanging("MappingID");
                    _MappingID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MappingID");
                    OnMappingIDChanged();
                }
            }
        }
        private global::System.Guid _MappingID;
        partial void OnMappingIDChanging(global::System.Guid value);
        partial void OnMappingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ProjectID
        {
            get
            {
                return _ProjectID;
            }
            set
            {
                OnProjectIDChanging(value);
                ReportPropertyChanging("ProjectID");
                _ProjectID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectID");
                OnProjectIDChanged();
            }
        }
        private Nullable<global::System.Guid> _ProjectID;
        partial void OnProjectIDChanging(Nullable<global::System.Guid> value);
        partial void OnProjectIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> BugID
        {
            get
            {
                return _BugID;
            }
            set
            {
                OnBugIDChanging(value);
                ReportPropertyChanging("BugID");
                _BugID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BugID");
                OnBugIDChanged();
            }
        }
        private Nullable<global::System.Guid> _BugID;
        partial void OnBugIDChanging(Nullable<global::System.Guid> value);
        partial void OnBugIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_ProjectBugsMapping_tbl_Bugs", "tbl_Bugs")]
        public tbl_Bugs tbl_Bugs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Bugs>("BugTrackerEntityModels.FK_tbl_ProjectBugsMapping_tbl_Bugs", "tbl_Bugs").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Bugs>("BugTrackerEntityModels.FK_tbl_ProjectBugsMapping_tbl_Bugs", "tbl_Bugs").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Bugs> tbl_BugsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Bugs>("BugTrackerEntityModels.FK_tbl_ProjectBugsMapping_tbl_Bugs", "tbl_Bugs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Bugs>("BugTrackerEntityModels.FK_tbl_ProjectBugsMapping_tbl_Bugs", "tbl_Bugs", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_ProjectBugsMapping_tbl_Projects", "tbl_Projects")]
        public tbl_Projects tbl_Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Projects>("BugTrackerEntityModels.FK_tbl_ProjectBugsMapping_tbl_Projects", "tbl_Projects").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Projects>("BugTrackerEntityModels.FK_tbl_ProjectBugsMapping_tbl_Projects", "tbl_Projects").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Projects> tbl_ProjectsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Projects>("BugTrackerEntityModels.FK_tbl_ProjectBugsMapping_tbl_Projects", "tbl_Projects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Projects>("BugTrackerEntityModels.FK_tbl_ProjectBugsMapping_tbl_Projects", "tbl_Projects", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackerEntityModels", Name="tbl_Projects")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Projects : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Projects object.
        /// </summary>
        /// <param name="projectID">Initial value of the ProjectID property.</param>
        public static tbl_Projects Createtbl_Projects(global::System.Guid projectID)
        {
            tbl_Projects tbl_Projects = new tbl_Projects();
            tbl_Projects.ProjectID = projectID;
            return tbl_Projects;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ProjectID
        {
            get
            {
                return _ProjectID;
            }
            set
            {
                if (_ProjectID != value)
                {
                    OnProjectIDChanging(value);
                    ReportPropertyChanging("ProjectID");
                    _ProjectID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProjectID");
                    OnProjectIDChanged();
                }
            }
        }
        private global::System.Guid _ProjectID;
        partial void OnProjectIDChanging(global::System.Guid value);
        partial void OnProjectIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Logo
        {
            get
            {
                return StructuralObject.GetValidValue(_Logo);
            }
            set
            {
                OnLogoChanging(value);
                ReportPropertyChanging("Logo");
                _Logo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Logo");
                OnLogoChanged();
            }
        }
        private global::System.Byte[] _Logo;
        partial void OnLogoChanging(global::System.Byte[] value);
        partial void OnLogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ApplicationType
        {
            get
            {
                return _ApplicationType;
            }
            set
            {
                OnApplicationTypeChanging(value);
                ReportPropertyChanging("ApplicationType");
                _ApplicationType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ApplicationType");
                OnApplicationTypeChanged();
            }
        }
        private global::System.String _ApplicationType;
        partial void OnApplicationTypeChanging(global::System.String value);
        partial void OnApplicationTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDate;
        partial void OnStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_ProjectBugsMapping_tbl_Projects", "tbl_ProjectBugsMapping")]
        public EntityCollection<tbl_ProjectBugsMapping> tbl_ProjectBugsMapping
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_ProjectBugsMapping>("BugTrackerEntityModels.FK_tbl_ProjectBugsMapping_tbl_Projects", "tbl_ProjectBugsMapping");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_ProjectBugsMapping>("BugTrackerEntityModels.FK_tbl_ProjectBugsMapping_tbl_Projects", "tbl_ProjectBugsMapping", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_UserProjectsMapping_tbl_Projects", "tbl_UserProjectsMapping")]
        public EntityCollection<tbl_UserProjectsMapping> tbl_UserProjectsMapping
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_UserProjectsMapping>("BugTrackerEntityModels.FK_tbl_UserProjectsMapping_tbl_Projects", "tbl_UserProjectsMapping");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_UserProjectsMapping>("BugTrackerEntityModels.FK_tbl_UserProjectsMapping_tbl_Projects", "tbl_UserProjectsMapping", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackerEntityModels", Name="tbl_UserProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_UserProfile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_UserProfile object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        public static tbl_UserProfile Createtbl_UserProfile(global::System.Guid userID)
        {
            tbl_UserProfile tbl_UserProfile = new tbl_UserProfile();
            tbl_UserProfile.UserID = userID;
            return tbl_UserProfile;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Guid _UserID;
        partial void OnUserIDChanging(global::System.Guid value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Firstname
        {
            get
            {
                return _Firstname;
            }
            set
            {
                OnFirstnameChanging(value);
                ReportPropertyChanging("Firstname");
                _Firstname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Firstname");
                OnFirstnameChanged();
            }
        }
        private global::System.String _Firstname;
        partial void OnFirstnameChanging(global::System.String value);
        partial void OnFirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Lastname
        {
            get
            {
                return _Lastname;
            }
            set
            {
                OnLastnameChanging(value);
                ReportPropertyChanging("Lastname");
                _Lastname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Lastname");
                OnLastnameChanged();
            }
        }
        private global::System.String _Lastname;
        partial void OnLastnameChanging(global::System.String value);
        partial void OnLastnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Displayname
        {
            get
            {
                return _Displayname;
            }
            set
            {
                OnDisplaynameChanging(value);
                ReportPropertyChanging("Displayname");
                _Displayname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Displayname");
                OnDisplaynameChanged();
            }
        }
        private global::System.String _Displayname;
        partial void OnDisplaynameChanging(global::System.String value);
        partial void OnDisplaynameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreationDate;
        partial void OnCreationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_Users_tbl_UserProfile", "tbl_Users")]
        public tbl_Users tbl_Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Users>("BugTrackerEntityModels.FK_tbl_Users_tbl_UserProfile", "tbl_Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Users>("BugTrackerEntityModels.FK_tbl_Users_tbl_UserProfile", "tbl_Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Users> tbl_UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Users>("BugTrackerEntityModels.FK_tbl_Users_tbl_UserProfile", "tbl_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Users>("BugTrackerEntityModels.FK_tbl_Users_tbl_UserProfile", "tbl_Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackerEntityModels", Name="tbl_UserProjectsMapping")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_UserProjectsMapping : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_UserProjectsMapping object.
        /// </summary>
        /// <param name="mappingID">Initial value of the MappingID property.</param>
        public static tbl_UserProjectsMapping Createtbl_UserProjectsMapping(global::System.Guid mappingID)
        {
            tbl_UserProjectsMapping tbl_UserProjectsMapping = new tbl_UserProjectsMapping();
            tbl_UserProjectsMapping.MappingID = mappingID;
            return tbl_UserProjectsMapping;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid MappingID
        {
            get
            {
                return _MappingID;
            }
            set
            {
                if (_MappingID != value)
                {
                    OnMappingIDChanging(value);
                    ReportPropertyChanging("MappingID");
                    _MappingID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MappingID");
                    OnMappingIDChanged();
                }
            }
        }
        private global::System.Guid _MappingID;
        partial void OnMappingIDChanging(global::System.Guid value);
        partial void OnMappingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private Nullable<global::System.Guid> _UserID;
        partial void OnUserIDChanging(Nullable<global::System.Guid> value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ProjectID
        {
            get
            {
                return _ProjectID;
            }
            set
            {
                OnProjectIDChanging(value);
                ReportPropertyChanging("ProjectID");
                _ProjectID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProjectID");
                OnProjectIDChanged();
            }
        }
        private Nullable<global::System.Guid> _ProjectID;
        partial void OnProjectIDChanging(Nullable<global::System.Guid> value);
        partial void OnProjectIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsMapped
        {
            get
            {
                return _IsMapped;
            }
            set
            {
                OnIsMappedChanging(value);
                ReportPropertyChanging("IsMapped");
                _IsMapped = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMapped");
                OnIsMappedChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsMapped;
        partial void OnIsMappedChanging(Nullable<global::System.Boolean> value);
        partial void OnIsMappedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_UserProjectsMapping_tbl_Projects", "tbl_Projects")]
        public tbl_Projects tbl_Projects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Projects>("BugTrackerEntityModels.FK_tbl_UserProjectsMapping_tbl_Projects", "tbl_Projects").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Projects>("BugTrackerEntityModels.FK_tbl_UserProjectsMapping_tbl_Projects", "tbl_Projects").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Projects> tbl_ProjectsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Projects>("BugTrackerEntityModels.FK_tbl_UserProjectsMapping_tbl_Projects", "tbl_Projects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Projects>("BugTrackerEntityModels.FK_tbl_UserProjectsMapping_tbl_Projects", "tbl_Projects", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_UserProjectsMapping_tbl_Users", "tbl_Users")]
        public tbl_Users tbl_Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Users>("BugTrackerEntityModels.FK_tbl_UserProjectsMapping_tbl_Users", "tbl_Users").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Users>("BugTrackerEntityModels.FK_tbl_UserProjectsMapping_tbl_Users", "tbl_Users").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Users> tbl_UsersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Users>("BugTrackerEntityModels.FK_tbl_UserProjectsMapping_tbl_Users", "tbl_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Users>("BugTrackerEntityModels.FK_tbl_UserProjectsMapping_tbl_Users", "tbl_Users", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackerEntityModels", Name="tbl_Users")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Users : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Users object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="isZsl">Initial value of the IsZsl property.</param>
        /// <param name="isActive">Initial value of the IsActive property.</param>
        public static tbl_Users Createtbl_Users(global::System.Guid userID, global::System.Boolean isZsl, global::System.Boolean isActive)
        {
            tbl_Users tbl_Users = new tbl_Users();
            tbl_Users.UserID = userID;
            tbl_Users.IsZsl = isZsl;
            tbl_Users.IsActive = isActive;
            return tbl_Users;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.Guid _UserID;
        partial void OnUserIDChanging(global::System.Guid value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsZsl
        {
            get
            {
                return _IsZsl;
            }
            set
            {
                OnIsZslChanging(value);
                ReportPropertyChanging("IsZsl");
                _IsZsl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsZsl");
                OnIsZslChanged();
            }
        }
        private global::System.Boolean _IsZsl;
        partial void OnIsZslChanging(global::System.Boolean value);
        partial void OnIsZslChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreationDate;
        partial void OnCreationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ModifiedDate
        {
            get
            {
                return _ModifiedDate;
            }
            set
            {
                OnModifiedDateChanging(value);
                ReportPropertyChanging("ModifiedDate");
                _ModifiedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedDate");
                OnModifiedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ModifiedDate;
        partial void OnModifiedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnModifiedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> UserTypeID
        {
            get
            {
                return _UserTypeID;
            }
            set
            {
                OnUserTypeIDChanging(value);
                ReportPropertyChanging("UserTypeID");
                _UserTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserTypeID");
                OnUserTypeIDChanged();
            }
        }
        private Nullable<global::System.Guid> _UserTypeID;
        partial void OnUserTypeIDChanging(Nullable<global::System.Guid> value);
        partial void OnUserTypeIDChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_Users_tbl_UserProfile", "tbl_UserProfile")]
        public tbl_UserProfile tbl_UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_UserProfile>("BugTrackerEntityModels.FK_tbl_Users_tbl_UserProfile", "tbl_UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_UserProfile>("BugTrackerEntityModels.FK_tbl_Users_tbl_UserProfile", "tbl_UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_UserProfile> tbl_UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_UserProfile>("BugTrackerEntityModels.FK_tbl_Users_tbl_UserProfile", "tbl_UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_UserProfile>("BugTrackerEntityModels.FK_tbl_Users_tbl_UserProfile", "tbl_UserProfile", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_UserProjectsMapping_tbl_Users", "tbl_UserProjectsMapping")]
        public EntityCollection<tbl_UserProjectsMapping> tbl_UserProjectsMapping
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_UserProjectsMapping>("BugTrackerEntityModels.FK_tbl_UserProjectsMapping_tbl_Users", "tbl_UserProjectsMapping");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_UserProjectsMapping>("BugTrackerEntityModels.FK_tbl_UserProjectsMapping_tbl_Users", "tbl_UserProjectsMapping", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_Users_tbl_UserType", "tbl_UserType")]
        public tbl_UserType tbl_UserType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_UserType>("BugTrackerEntityModels.FK_tbl_Users_tbl_UserType", "tbl_UserType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_UserType>("BugTrackerEntityModels.FK_tbl_Users_tbl_UserType", "tbl_UserType").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_UserType> tbl_UserTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_UserType>("BugTrackerEntityModels.FK_tbl_Users_tbl_UserType", "tbl_UserType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_UserType>("BugTrackerEntityModels.FK_tbl_Users_tbl_UserType", "tbl_UserType", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackerEntityModels", Name="tbl_UserType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_UserType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_UserType object.
        /// </summary>
        /// <param name="userTypeID">Initial value of the UserTypeID property.</param>
        public static tbl_UserType Createtbl_UserType(global::System.Guid userTypeID)
        {
            tbl_UserType tbl_UserType = new tbl_UserType();
            tbl_UserType.UserTypeID = userTypeID;
            return tbl_UserType;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid UserTypeID
        {
            get
            {
                return _UserTypeID;
            }
            set
            {
                if (_UserTypeID != value)
                {
                    OnUserTypeIDChanging(value);
                    ReportPropertyChanging("UserTypeID");
                    _UserTypeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserTypeID");
                    OnUserTypeIDChanged();
                }
            }
        }
        private global::System.Guid _UserTypeID;
        partial void OnUserTypeIDChanging(global::System.Guid value);
        partial void OnUserTypeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TypeName
        {
            get
            {
                return _TypeName;
            }
            set
            {
                OnTypeNameChanging(value);
                ReportPropertyChanging("TypeName");
                _TypeName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TypeName");
                OnTypeNameChanged();
            }
        }
        private global::System.String _TypeName;
        partial void OnTypeNameChanging(global::System.String value);
        partial void OnTypeNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackerEntityModels", "FK_tbl_Users_tbl_UserType", "tbl_Users")]
        public EntityCollection<tbl_Users> tbl_Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_Users>("BugTrackerEntityModels.FK_tbl_Users_tbl_UserType", "tbl_Users");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_Users>("BugTrackerEntityModels.FK_tbl_Users_tbl_UserType", "tbl_Users", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
